spring.jpa.database: "MYSQL"
spring.datasource.platform:  "mysql"
spring.jpa.show-sql: "true"
spring.database.driverClassName: "com.mysql.jdbc.Driver"
spring.datasource.url: "jdbc:mysql://192.168.43.104:3306/spmia?serverTimezone=GMT%2B8&characterEncoding=utf-8&allowPublicKeyRetrieval=true&useSSL=false"
spring.datasource.driver-class-name: "com.mysql.jdbc.Driver"
spring.datasource.username: "root"
#spring.datasource.password: "{cipher}9a2342e53df0f3fbf16e4e054efe3543972099dfe654fbe8f70d37f2147988d3"
#104-dev123
spring.datasource.password: "{cipher}3fb467c6a9f0445e242bc123e6f8797e33fde8bdd3cf0328bdb06c113acaf8c6"
spring.datasource.testWhileIdle: "true"
spring.datasource.validationQuery: "SELECT 1"
#spring.jpa.properties.hibernate.dialect: "org.hibernate.dialect.PostgreSQLDialect"
signing.key: "345345fsdfsf5345"
auth.security.encode.mode: "bcrypt"
